services:
  app:
    build: ./docker/php
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
    # environment:
    #   - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      # - "8080:80"
      - "8443:443"  # HTTPSで使うポート
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl  # 証明書をNginxにマウント
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: hkcdiary
      MYSQL_ROOT_PASSWORD: U7v7iRNe3HNz
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
  node:
    # image: node:20
    build:
      context: .                                # ← プロジェクトルートを明示
      dockerfile: docker/node/Dockerfile
    container_name: laravel_node
    working_dir: /var/www
    # volumes:
    #   - ./:/var/www
    volumes:
    - .:/var/www:cached
    command: tail -f /dev/null
    # command: sh -c "npm install && npm run dev"
    ports:
    - "5173:5173"
    depends_on:
      - app
    networks:
      - laravel
volumes:
  dbdata:

networks:
  laravel:
    driver: bridge